name: Spell Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Install Dependencies (cspell)
        run: npm install cspell@latest

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - name: Execute Spell Check and report with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cspell $(git diff remotes/origin/$GITHUB_BASE_REF --name-only) --config .cspell.json | \
          reviewdog -efm="%f:%l:%c - %m" -reporter=github-pr-review -level=warning